### PR TITLE
Update kernel-alt to match upstream 4.19.309

### PR DESCRIPTION
**Pull request by rushikeshjadhav**

### CODE REVIEW

**Comment by stormi** [comment]
Why is there a merge commit in the pull request?

**Comment by stormi** [comment]
Ping

**Comment by rushikeshjadhav** [comment]
I'll remove the merge commit and fast forward. However, I'm still working on the new patches that came in kernel repo which may apply here. Might need another week close this.

**Comment by rushikeshjadhav** [comment]
Hi @stormi There is a 13 patch series in new kernel repo where it adds support for auxiliary bus. The code "ADD_TO_DEVTABLE" in it has been removed for a different implementation. Ref. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/scripts/mod/file2alias.c?h=v4.19.311&id=aa0e8cc9d7a89bb0c23435ec1b62eac46b1f4984 however XS8.3 has not yet implemented this. What do you recommend in this situation for kernel-alt?  Do we modify the patch code or do we not offer auxiliary bus support in kernel-alt.

```
#Patch571: 0001-Add-auxiliary-bus-support.patch
#Patch572: 0002-driver-core-auxiliary-bus-move-slab.h-from-include-f.patch
#Patch573: 0003-driver-core-auxiliary-bus-make-remove-function-retur.patch
#Patch574: 0004-driver-core-auxiliary-bus-minor-coding-style-tweaks.patch
#Patch575: 0005-driver-core-auxiliary-bus-Fix-auxiliary-bus-shutdown.patch
#Patch576: 0006-driver-core-auxiliary-bus-Fix-calling-stage-for-auxi.patch
#Patch577: 0007-driver-core-auxiliary-bus-Remove-unneeded-module-bit.patch
#Patch578: 0008-driver-core-auxiliary-bus-Fix-memory-leak-when-drive.patch
#Patch579: 0009-Documentation-auxiliary_bus-Clarify-auxiliary_device.patch
#Patch580: 0010-Documentation-auxiliary_bus-Clarify-__auxiliary_driv.patch
#Patch581: 0011-Documentation-auxiliary_bus-Clarify-the-release-of-d.patch
#Patch582: 0012-Documentation-auxiliary_bus-Move-the-text-into-the-c.patch
#Patch583: 0013-CP-41018-Make-CONFIG_AUXILIARY_BUS-y-work.patch
```

**Comment by stormi** [comment]
I forwarded your question to @tescande. 

Regarding the state of the PR, github indicates it has conflicts with the current state of origin/master, and probably needs rebasing. (Update: but I understand from your previous messages that you are aware and are going to rebase when everything is ready?)

**Comment by tescande** [comment]
Hi @rushikeshjadhav,

I'm not sure to understand the link between the "ADD_TO_DEVTABLE" patches and the auxiliary bus patchset.

If I get it correctly, the 2 patches `modpost: Add-auxiliary-bus-support.patch` and `modpost: file2alias: check prototype of handler` have been backported since `v4.19.37` so the patches can be ignored.

For the Auxiliary bus support, the patchset should be included in the kernel-alt.

**Comment by rushikeshjadhav** [comment]
Hi @tescande 

Highlighted patch queue is introduced for auxiliary bus support in XS kernel. It's a set of 13 patches to be applied together. (`Subject: [PATCH 01/13] Add auxiliary bus support`)

This driver is not present in kernel.org 4.19.x ref https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/base?h=v4.19.312 hence kernel 4.19.x does not have support for macro "ADD_TO_DEVTABLE" and auxiliary bus driver. 

If this has to work then we need to modify `0001-Add-auxiliary-bus-support.patch` in compliance with kernel.org 4.19.x or wait for it to be available in kernel.org 4.19.x tree. I recommend deciding this based on relevance of auxiliary bus support in XCP-ng. If we do decide to make it available then I would request a pull without it and then another pull specially on this modified patch-set to support auxiliary bus. Let me know your thoughts.

**Comment by tescande** [comment]
If I get it correctly, the patch `0001-Add-auxiliary-bus-support.patch` has to be slightly modify to be integrated.

The following line should be removed
```
ADD_TO_DEVTABLE("auxiliary", auxiliary_device_id, do_auxiliary_entry);
```

And an entry added in `static const struct devtable devtable[]` (line ~1309) as:
```
	{"auxiliary", SIZE_auxiliary_device_id, do_auxiliary_entry},
```

**Comment by rushikeshjadhav** [comment]
@tescande You may refer the updated PR https://github.com/xcp-ng-rpms/kernel-alt/pull/23 I have retained the `ADD_TO_DEVTABLE` macro and kept the auxiliary bus support.

**Pull request closed without merging**
